
# A string used to distinguish different Supabase projects on the same host. Defaults to the working
# directory name when running `supabase init`.
project_id = "hcaqodjylicmppxcbqbh"

[api]
# Port to use for the API URL.
port = 54321
# Schemas to expose in your API. Tables, views and stored procedures in this schema will get API
# endpoints. public and storage are always included.
schemas = ["public", "storage", "extensions"]
# Extra schemas to add to the search_path of every request. public is always included.
extra_search_path = ["public", "extensions"]
# Maximum rows returns from a view, table, or stored procedure. Limits payload size for accidental
# large queries. Default is 1000.
max_rows = 1000

[db]
# Port to use for the local database URL.
port = 54322
# The database major version to use. This has to be the same as your remote database's. Run `SHOW
# server_version;` on the remote database to check.
major_version = 15

[studio]
# Port to use for Supabase Studio.
port = 54323

# Email testing server. Emails sent with the local dev setup are not actually sent - rather, they
# are monitored, and you can view the emails that would have been sent from the web interface.
[inbucket]
# Port to use for the email testing server web interface.
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
# The maximum file size allowed (e.g. "5MB", "500KB").
file_size_limit = "50MiB"

[auth]
# The base URL of your website. Used as an allow-list for redirects and for constructing URLs used
# in emails.
site_url = "http://localhost:3000"
# A list of *exact* URLs that auth providers are permitted to redirect to post authentication.
additional_redirect_urls = ["https://localhost:3000"]
# How long tokens are valid for, in seconds. Defaults to 3600 (1 hour), maximum 604,800 seconds (one
# week).
jwt_expiry = 3600
# Allow/disallow new user signups to your project.
enable_signup = true
# If disabled, the first user to sign up will be the superadmin.
enable_confirmations = false

# Configure one of the supported auth providers to enable it for your project.
# Enable these to use your own OAuth providers in the auth component
# The backend is configured with dummy values to facilitate local testing
# Complete override of the auth provider config with the gotrue config
[auth.external.google]
enabled = false
client_id = "env(GOOGLE_CLIENT_ID)"
secret = "env(GOOGLE_CLIENT_SECRET)"
# Overrides the default auth redirectUrl.
redirect_uri = ""
# Overrides the default auth provider URL. Used to support self-hosted gitlab, single-tenant Azure,
# or any other third-party OIDC providers.
url = ""

[auth.external.facebook]
enabled = false
client_id = "env(FACEBOOK_CLIENT_ID)"
secret = "env(FACEBOOK_CLIENT_SECRET)"
# Overrides the default auth redirectUrl.
redirect_uri = ""
# Overrides the default auth provider URL. Used to support custom OIDC providers.
url = ""

[analytics]
enabled = false
port = 54327
vector_port = 54328
# Configure one of the supported backends
backend = "postgres"

# Configure rate limiting for the API. Specifying false disables rate limiting.
[api.rate_limits]
enabled = false

# Enable, configure edge functions
[functions]
enabled = true
serve_floats_as_strings = false

[functions.doctor-ai-assistant]
verify_jwt = true
import_map = "supabase/functions/import_map.json"

[functions.care-team-ai-chat]
verify_jwt = true
import_map = "supabase/functions/import_map.json"

[functions.send-health-plan-reminders]
verify_jwt = true
import_map = "supabase/functions/import_map.json"
