
project_id = "hcaqodjylicmppxcbqbh"
[functions.sync-care-team-rooms]
verify_jwt = true
[functions.verify-users-exist]
verify_jwt = true
[functions.send-chat-message]
verify_jwt = true
[functions.get-patient-care-team-room]
verify_jwt = true

