
project_id = "hcaqodjylicmppxcbqbh"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
port = 54323

[functions.send-whatsapp-notification]
verify_jwt = true

[functions.analyze-medical-document]
verify_jwt = true
