
project_id = "hcaqodjylicmppxcbqbh"

[api]
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
port = 54329
pool_mode = "transaction"
default_pool_size = 15
max_client_conn = 100

[realtime]
enabled = true

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
file_size_limit = 50000000

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true

[auth.external.apple]
enabled = false
client_id = ""
secret = ""
redirect_uri = "http://localhost:3000"

[auth.external.azure]
enabled = false
client_id = ""
secret = ""
url = ""
redirect_uri = "http://localhost:3000"

[auth.external.bitbucket]
enabled = false
client_id = ""
secret = ""
redirect_uri = "http://localhost:3000"

[auth.external.discord]
enabled = false
client_id = ""
secret = ""
redirect_uri = "http://localhost:3000"

[auth.external.facebook]
enabled = false
client_id = ""
secret = ""
redirect_uri = "http://localhost:3000"

[auth.external.github]
enabled = false
client_id = ""
secret = ""
redirect_uri = "http://localhost:3000"

[auth.external.gitlab]
enabled = false
client_id = ""
secret = ""
redirect_uri = "http://localhost:3000"

[auth.external.google]
enabled = false
client_id = ""
secret = ""
redirect_uri = "http://localhost:3000"

[auth.external.keycloak]
enabled = false
client_id = ""
secret = ""
url = ""
redirect_uri = "http://localhost:3000"

[auth.external.linkedin]
enabled = false
client_id = ""
secret = ""
redirect_uri = "http://localhost:3000"

[auth.external.spotify]
enabled = false
client_id = ""
secret = ""
redirect_uri = "http://localhost:3000"

[auth.external.twitch]
enabled = false
client_id = ""
secret = ""
redirect_uri = "http://localhost:3000"

[auth.external.twitter]
enabled = false
client_id = ""
secret = ""
redirect_uri = "http://localhost:3000"

[auth.external.workos]
enabled = false
client_id = ""
secret = ""
redirect_uri = "http://localhost:3000"

[analytics]
enabled = false
port = 54327
vector_port = 54328

[functions]
[functions.bhashini-translate]
verify_jwt = false
[functions.send-whatsapp-notification]
verify_jwt = false
