
hcaqodjylicmppxcbqbh

[functions.doctor-ai-assistant]
verify_jwt = true

[functions.get-assigned-patients]
verify_jwt = true

[functions.get-chat-messages]
verify_jwt = true

[functions.get-doctor-for-patient]
verify_jwt = true

[functions.get-nutritionist-for-patient]
verify_jwt = true

[functions.get-medical-report-url]
verify_jwt = true

[functions.get-patient-care-team]
verify_jwt = true

[functions.get-patient-profile]
verify_jwt = true

[functions.mark-messages-as-read]
verify_jwt = true

[functions.send-chat-message]
verify_jwt = true

[functions.send-health-plan-notification]
verify_jwt = true

[functions.send-health-plan-reminders]
verify_jwt = true

[functions.send-whatsapp-notification]
verify_jwt = true

[functions.upsert-patient-details]
verify_jwt = true

[functions.upsert-user-role]
verify_jwt = true

[functions.admin-assign-care-team]
verify_jwt = true

[functions.admin-assign-doctor-to-patient]
verify_jwt = true

[functions.admin-assign-nutritionist-to-patient]
verify_jwt = true
