
project_id = "hcaqodjylicmppxcbqbh"

[api]
enabled = true

[db]
enabled = true

[analytics]
enabled = false

[functions]
enabled = true

[functions.admin-setup-nutritionist-as-default]
verify_jwt = true

[functions.send-comprehensive-welcome-notification]
verify_jwt = true

[functions.sync-care-team-rooms]
verify_jwt = true

[functions.auth-user-created-hook]
verify_jwt = false

[auth]
[auth.hooks]
[auth.hooks.user_created]
enabled = true
url = "https://hcaqodjylicmppxcbqbh.supabase.co/functions/v1/auth-user-created-hook"
