
project_id = "hcaqodjylicmppxcbqbh"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_expiry = 43200
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[auth.external.apple]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""

[auth.external.azure]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""

[auth.external.bitbucket]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""

[auth.external.discord]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""

[auth.external.facebook]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""

[auth.external.github]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""

[auth.external.gitlab]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""

[auth.external.google]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""

[auth.external.keycloak]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""

[auth.external.linkedin]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""

[auth.external.notion]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""

[auth.external.twitch]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""

[auth.external.twitter]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""

[auth.external.slack]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""

[auth.external.spotify]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""

[auth.external.workos]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""

[analytics]
enabled = false
port = 54327
vector_port = 54328
backend = "postgres"

[experimental]
pubsub = false
graphql_plan_cache = false

[functions]
[functions.care-team-ai-chat]
verify_jwt = true
